### ISSUE TITLE
deepaa_output.pyを実行時にmodel_from_jsonで実行時例外が発生しますー。

### ISSUE THREAD

**Issue by umyuu** [OsciiArt/DeepAA#2]
pip でtensorflowとKerasはインストールしましたー。

#スタックトレース
> Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/(ユーザー名)/Downloads/DeepAA-master/deepaa_output.py", line 24, in <module>
    model = model_from_json(json_string)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\models.py", line 325, in model_from_json
    return layer_module.deserialize(config, custom_objects=custom_objects)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 140, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2370, in from_config
    process_layer(layer_data)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py", line 2339, in process_layer
    custom_objects=custom_objects)
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\layers\__init__.py", line 46, in deserialize
    printable_module_name='layer')
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\utils\generic_utils.py", line 141, in deserialize_keras_object
    return cls.from_config(config['config'])
  File "C:\Program Files\Anaconda3\lib\site-packages\keras\engine\topology.py", line 1202, in from_config
    return cls(**config)
TypeError: __init__() got an unexpected keyword argument 'input_dtype'

#環境
Python 3.5.2 |Anaconda custom (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
依存ライブラリのバージョン
- tensorflow (1.0.1)
- Keras (2.0.1)
- numpy (1.12.0)
- Pillow (3.3.1)

**Comment by umyuu** [comment]
model\model_01\model.json　のファイルを見たら原因が分かりましたー。

> keras_version": "1.2.0

手元の環境でpipでインストールしたKerasのバージョンが原因でした、申し訳ないですー。
○pip install keras==1.2.0
×pip install keras

**Comment by OsciiArt** [comment]
報告ありがとうございます。readmeにバージョンについて追記しておきます。

PRの方確認中です。もう少々お待ちください。
